general:
  backup_location: backups
  log_location: logs
  log_level: INFO
  retention_policy_days: 7
  backup_schedule: "0 3 * * *"

destinations:
  local:
    enabled: true
    path: backups

  s3:
    enabled: false
    bucket_name: backupbee
    region: us-east-1
    access_key: XXXXXXXXXXX
    secret_key: XXXXXXXXXXX

  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    smtp_username:
    smtp_password:

notifications:
  email:
    enabled: true
    from: no-reply@backupbee.com
    to:
      - master@backupbee.com

  slack:
    enabled: false
    webhook_url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX

  webhook:
    enabled: false
    url: https://backupbee.com/api/v1/backup

  discord:
    enabled: true
    webhook_url: https://discord.com/api/webhooks/XXXXXXXXX/XXXXXXXXX

databases:
  - name: primary_db
    type: postgres
    host: localhost
    port: 5432
    username: postgres
    password: pass
    database_name: asterconsult
    backup_schedule: "0 3 * * *"

  # - name: secondary_db
  #   type: mysql
  #   host: 192.168.1.10
  #   port: 3306
  #   username: backup_user
  #   password: supersecret
  #   database_name: my_secondary_db
  #   backup_schedule: "0 4 * * *"
