export const NOTIFICATION = {
  SLACK: "SLACK",
  CUSTOM: "CUSTOM",
  DISCORD: "DISCORD",
  TELEGRAM: "TELEGRAM",
};

export const DESTINATION = {
  EMAIL: "EMAIL",
  S3_BUCKET: "S3_BUCKET",
  LOCAL: "LOCAL",
};
